version: '3.8'

services:
  # Back-end servisi
  api-server:
    build: ./back-end
    ports:
      - "5000:5000"

  # Front-end servisi
  web-server:
    build: ./front-end
    ports:
      - "80:80"
    # Front-end back-end-dən asılıdır, ona görə gözləməlidir
    depends_on:
      - api-server