server {
    listen 80;

    # Ana səhifəyə gələn istəkləri Front-end-ə göndər
    location / {
        proxy_pass http://web-server:80;
    }

    # /api ilə başlayan istəkləri Back-end-ə göndər
    location /api {
        proxy_pass http://api-server:5000/;
    }
}